import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  intercomSidebar: [
		{
			type: 'doc',
			id: 'intercom/intro',
			label: 'Overview',
		}, {
			type: 'category',
			label: 'Lanscape of Solutions',
			link: {
				type: "doc",
				id: 'intercom/landscape/intro',
			},
			collapsible: true,
			items: [
				'intercom/landscape/topologies',
				'intercom/landscape/routers',
			]
		}, {
			type: 'category',
			label: 'Communication Paradigms',
			link: {
				type: "doc",
				id: 'intercom/paradigms/intro',
			},
			collapsible: true,
			items: [
				'intercom/paradigms/intrachain',
				'intercom/paradigms/intercontract',
				'intercom/paradigms/orchestrator',
				'intercom/paradigms/intents',
			]
		}, {
			type: 'category',
			label: 'Trust Models',
			link: {
				type: "doc",
				id: 'intercom/trust/intro',
			},
			collapsible: true,
			items: [
				'intercom/trust/trusted',
				'intercom/trust/minimized',
				'intercom/trust/trustless',
			]
		}, {
			type: 'doc',
			id: 'intercom/usecases',
			label: 'Communication Use Cases',
		}, {
			type: 'html',
      value: '<div style="border: 1px solid #dee2e6; margin: 1rem;"/>',
		}, {
			type: 'doc',
			id: 'intercom/messaging',
			label: 'Contract To Contract Messaging',
		}, {
			type: 'category',
			label: 'Messaging Agents',
			link: {
				type: "doc",
				id: 'intercom/agents/intro',
			},
			collapsible: true,
			items: [
				'intercom/agents/relayers',
				'intercom/agents/validators',
				'intercom/agents/provers',
			]
		}, {
			type: 'category',
			label: 'Communication Models',
			link: {
				type: "doc",
				id: 'intercom/communication/intro',
			},
			collapsible: true,
			items: [
				'intercom/communication/1way',
				'intercom/communication/2way',
			]
		}, {
			type: 'category',
			label: 'Execution Models',
			link: {
				type: "doc",
				id: 'intercom/execution/intro',
			},
			collapsible: true,
			items: [
				'intercom/execution/retry',
				'intercom/execution/saga',
			]
		}, {
			type: 'category',
			label: 'Messaging Use Cases',
			link: {
				type: "doc",
				id: 'intercom/usecases/intro',
			},
			collapsible: true,
			items: [
				'intercom/usecases/state',
				'intercom/usecases/execution',
				'intercom/usecases/bridge',
				'intercom/usecases/payments',
				'intercom/usecases/swap',
			]
		}, 
	],
  adaptersSidebar: [
		{
			type: 'doc',
			id: 'adapters/intro',
			label: 'ERC-7786 Standard',
		}, {
			type: 'doc',
			id: 'adapters/adapters',
			label: 'ERC-7786 Adapters',
		}, 
	],

};

export default sidebars;
