import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  intercomSidebar: [
		{
			type: 'doc',
			id: 'intercom/intro',
			label: 'Intro',
		}, {
			type: 'category',
			label: 'Landscape',
			link: {
				type: "doc",
				id: 'intercom/landscape/intro',
			},
			collapsible: true,
			items: [
				'intercom/landscape/relayers',
				'intercom/landscape/routers',
				'intercom/landscape/sequencers',
			]
		}, {
			type: 'category',
			label: 'Topologies',
			link: {
				type: "doc",
				id: 'intercom/topologies/intro',
			},
			collapsible: true,
			items: [
				'intercom/topologies/intro',
			]
		}, {
			type: 'category',
			label: 'Interop Paradigms',
			link: {
				type: "doc",
				id: 'intercom/paradigms/intro',
			},
			collapsible: true,
			items: [
				'intercom/paradigms/intrachain',
				'intercom/paradigms/offchain',
				'intercom/paradigms/onchain',
				'intercom/paradigms/intents',
			]
		}, {
			type: 'html',
      value: '<div style="border: 1px solid #dee2e6; margin: 1rem;"/>',
		}, {
			type: 'doc',
			id: 'intercom/p2ponchain',
			label: 'P2P Onchain Communication',
		}, {
			type: 'category',
			label: 'Communication Models',
			link: {
				type: "doc",
				id: 'intercom/communication/intro',
			},
			collapsible: true,
			items: [
				'intercom/communication/1way',
				'intercom/communication/2way',
			]
		}, {
			type: 'category',
			label: 'Execution Models',
			link: {
				type: "doc",
				id: 'intercom/execution/intro',
			},
			collapsible: true,
			items: [
				'intercom/execution/atomic',
				'intercom/execution/saga',
				'intercom/execution/retry',
			]
		}, {
			type: 'category',
			label: 'Trust Models',
			link: {
				type: "doc",
				id: 'intercom/trust/intro',
			},
			collapsible: true,
			items: [
				'intercom/trust/trusted',
				'intercom/trust/minimized',
				'intercom/trust/trustless',
			]
		}, {
			type: 'category',
			label: 'Use Cases',
			link: {
				type: "doc",
				id: 'intercom/usecases/intro',
			},
			collapsible: true,
			items: [
				{
					type: 'category',
					label: 'Token Use Cases',
					link: {
						type: "doc",
						id: 'intercom/usecases/token/intro',
					},
					collapsible: true,
					items: [
						'intercom/usecases/token/clone',
						'intercom/usecases/token/masterslave',
						'intercom/usecases/token/messaging',
					]
				}, 
				{
					type: 'category',
					label: 'Issuer Use Cases',
					link: {
						type: "doc",
						id: 'intercom/usecases/issuer/intro',
					},
					collapsible: true,
					items: [
						{
							type: 'category',
							label: 'Token Design',
							link: {
								type: "doc",
								id: 'intercom/usecases/issuer/capture/intro',
							},
							collapsible: true,
							items: [
								'intercom/usecases/issuer/capture/speculative',
								'intercom/usecases/issuer/capture/utility',
								'intercom/usecases/issuer/capture/intrinsic',
							]
						}, 
						{
							type: 'category',
							label: 'Network Presence',
							link: {
								type: "doc",
								id: 'intercom/usecases/issuer/presence/intro',
							},
							collapsible: true,
							items: [
								'intercom/usecases/issuer/presence/creation',
								'intercom/usecases/issuer/presence/onboarding',
								'intercom/usecases/issuer/presence/rebalancing',
								'intercom/usecases/issuer/presence/withdrawing',
							]
						}, 
						{
							type: 'category',
							label: 'DeFi Services',
							link: {
								type: "doc",
								id: 'intercom/usecases/issuer/defi/intro',
							},
							collapsible: true,
							items: [
								'intercom/usecases/issuer/defi/exchanges',
								'intercom/usecases/issuer/defi/staking',
								'intercom/usecases/issuer/defi/lending',
							]
						}, 
					]
				}, 
				{
					type: 'category',
					label: 'Holder Use Cases',
					link: {
						type: "doc",
						id: 'intercom/usecases/holder/intro',
					},
					collapsible: true,
					items: [
						{
							type: 'category',
							label: 'Network Presence',
							link: {
								type: "doc",
								id: 'intercom/usecases/holder/presence/intro',
							},
							collapsible: true,
							items: [
								'intercom/usecases/holder/presence/moving',
							]
						}, {
							type: 'category',
							label: 'Operation',
							link: {
								type: "doc",
								id: 'intercom/usecases/holder/operation/intro',
							},
							collapsible: true,
							items: [
								'intercom/usecases/holder/operation/transfer',
								'intercom/usecases/holder/operation/swap',
							]
						}, {
							type: 'category',
							label: 'Retail',
							link: {
								type: "doc",
								id: 'intercom/usecases/holder/retail/intro',
							},
							collapsible: true,
							items: [
								'intercom/usecases/holder/retail/payments',
							]
						}, 
					]
				}, {
					type: 'category',
					label: 'Intends Use Cases',
					link: {
						type: "doc",
						id: 'intercom/usecases/intends/intro',
					},
					collapsible: true,
					items: [
						'intercom/usecases/intends/solvers',
					]
				}, 
				{
					type: 'doc',
					id: 'intercom/usecases/bridge',
					label: 'Bridge Pattern',
				}, 
			]
		}, 
	],
  adaptersSidebar: [
		{
			type: 'doc',
			id: 'adapters/intro',
			label: 'Adapters',
		}, 
	],

};

export default sidebars;
